# Generated by Django 3.2.9 on 2021-11-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20211122_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='game',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
